name: loan-scholar-opt
services:
  - name: frontend
    github:
      repo: your-username/loan-scholar-opt
      branch: master
      deploy_on_push: true
    build_command: cd frontend && npm install && npm run build
    run_command: cd frontend && npm start
    http_port: 3000
    envs:
      - key: NUXT_PUBLIC_SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${NUXT_PUBLIC_SUPABASE_URL}
      - key: NUXT_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${NUXT_PUBLIC_SUPABASE_ANON_KEY}
      - key: NUXT_API_BASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${NUXT_API_BASE_URL}
    health_check:
      http_path: /
    
  - name: backend
    github:
      repo: your-username/loan-scholar-opt
      branch: master
      deploy_on_push: true
    build_command: cd backend/telegram-scraper && npm install
    run_command: cd backend/telegram-scraper && npm start
    http_port: 3001
    envs:
      - key: SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${SUPABASE_URL}
      - key: SUPABASE_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${SUPABASE_KEY}
      - key: TELEGRAM_API_ID
        scope: RUN_AND_BUILD_TIME
        value: ${TELEGRAM_API_ID}
      - key: TELEGRAM_API_HASH
        scope: RUN_AND_BUILD_TIME
        value: ${TELEGRAM_API_HASH}
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "3001"
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
    health_check:
      http_path: /health
