name: loan-scholar-opt
services:
  - name: frontend
    github:
      repo: your-username/loan-scholar-opt
      branch: master
      deploy_on_push: true
    build_command: bash build-frontend.sh
    run_command: bash start-frontend.sh
    http_port: 3000
    envs:
      - key: NUXT_PUBLIC_SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${NUXT_PUBLIC_SUPABASE_URL}
      - key: NUXT_PUBLIC_SUPABASE_ANON_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${NUXT_PUBLIC_SUPABASE_ANON_KEY}
      - key: NUXT_API_BASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${NUXT_API_BASE_URL}
    health_check:
      http_path: /
    alerts:
      - rule: CPU_UTILIZATION
        value: 75
      - rule: MEM_UTILIZATION
        value: 80
    
  - name: backend
    github:
      repo: your-username/loan-scholar-opt
      branch: master
      deploy_on_push: true
    build_command: bash build-backend.sh
    run_command: bash start-backend.sh
    http_port: 3001
    envs:
      - key: SUPABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${SUPABASE_URL}
      - key: SUPABASE_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${SUPABASE_KEY}
      - key: TELEGRAM_API_ID
        scope: RUN_AND_BUILD_TIME
        value: ${TELEGRAM_API_ID}
      - key: TELEGRAM_API_HASH
        scope: RUN_AND_BUILD_TIME
        value: ${TELEGRAM_API_HASH}
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "3001"
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
    health_check:
      http_path: /health
    alerts:
      - rule: CPU_UTILIZATION
        value: 80
      - rule: MEM_UTILIZATION
        value: 85
